### PR TITLE
Tell Zeitwerk to ignore `app/overrides` in Rails 6

### PR DESCRIPTION
**Pull request by aldesantis**
Currently, Ruby overrides (`app/overrides/*.rb`) don't work properly with Rails 6 and Zeitwerk, because Zeitwerk expects each Ruby file under `app` (or any other autoloaded path) to define its corresponding constant. With this patch, we tell Zeitwerk to ignore `app/overrides` in all Railties.

Removing these paths from `eager_load_paths`, as Deface is currently doing, is not enough, because Zeitwerk will still ensure that each file under an autoloaded path follows its conventions (see [how it overrides `Kernel#require`](https://github.com/fxn/zeitwerk/blob/47fc4c82096dc4e55041cd1c6e61c3492876261b/lib/zeitwerk/kernel.rb#L13)).

### CODE REVIEW

**Comment by aldesantis** [comment]
Actually, I just saw https://github.com/spree/deface/blob/master/lib/deface/railtie.rb#L36. 🤦‍♂ However, it doesn't seem to work for us and `app/overrides` is still being eager-loaded and throwing errors.

**Comment by aldesantis** [comment]
@damianlegawiec I believe this is now ready. The missing piece in the existing initializer is that Zeitwerk will still run its checks when we `require` the files in `app/overrides`, unless we explicitly tell it to ignore that directory.

**Comment by damianlegawiec** [comment]
Thank you @aldesantis 👍

**Comment by kennyadsl** [comment]
Hey there! 👋 Is there any plan to release a new Deface version with this fix?

**Pull request merged**
